apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 844953406820.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newName: 844953406820.dkr.ecr.us-east-2.amazonaws.com/demo-frontend
  newTag: 4ce2bf17
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
